// Arquivo: app/layout.tsx

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./src/contexts/AuthContext";
import MenuLateral from "./menu/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // A tag <html> deve ser o elemento raiz
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      {/* A tag <body> vem em seguida */}
      <body style={{ display: 'flex' }}>
        {/* O AuthProvider fica DENTRO do body, envolvendo os componentes */}
        <AuthProvider>
          <MenuLateral />
          {children} {/* {children} é onde a sua page.tsx será renderizada */}
        </AuthProvider>
      </body>
    </html>
  );
}