// Arquivo: app/layout.tsx

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./contexts/AuthContext";
import MenuLateral from "./menu/page";
import ButtonAppBar from "./component/appBar/ButtonAppBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>

      <body style={{display: 'flex', width: '100%', height: '100vh', position: 'relative', }}>
        <AuthProvider>

          <div style={{ width: '100%', overflow:'hidden'  }}>
            <ButtonAppBar />

            <div style={{position: 'relative', display: 'flex', flexDirection: 'column', overflow: 'auto', height:'80%'}}>
               {children}
            </div>
          <div style={{height: '10%', background: 'var(--gray)'}}>
            Footer
          </div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}