// ./cliente-pixel/Jenkinsfile - Versão Final com Caminho Absoluto

pipeline {
    agent any
    environment {
    SERVICE_NAME = 'nginx'
}

    stages {
        stage('Deploy do Serviço') {
            steps {
                script {
                    echo "Parando e reconstruindo o serviço ${SERVICE_NAME}..."
                    sh 'docker-compose -f /var/jenkins_home/workspace/job-cliente-pixel/docker-compose.yml up -d --build'
                }
            }
        }
    }
    post {
        always {
            mail to: 'emilycaroline689@gmail.com',
                 subject: "Jenkins Job: ${currentBuild.fullDisplayName} - ${currentBuild.currentResult}",
                 body: "O Job ${env.JOB_NAME} (${SERVICE_NAME}) foi concluído.\n\nStatus: ${currentBuild.currentResult}.\n\nPara mais detalhes, acesse: ${env.BUILD_URL}"
        }
    }
}