version: '3.8'
services:
  jenkins:
    # A linha 'image: jenkins/jenkins:lts-jdk17' foi substituída por esta seção 'build':
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    container_name: jenkins_controller
    privileged: true
    user: root
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker

volumes:
  jenkins_data: