// ./api-node-pixel/Jenkinsfile - Versão Final com Caminho Absoluto

pipeline {
    agent any
    environment {
        SERVICE_NAME = 'api-node-pixel'
    }
    stages {
        stage('Deploy do Serviço') {
            steps {
                script {
                    ls
                    echo "Build da imagem ${SERVICE_NAME}..."
                    //sh "docker compose -f ${env.WORKSPACE}/docker-compose.yml up -d --build ${SERVICE_NAME}"
                    docker build -t ${SERVICE_NAME} .
                }
            }
        }
    }
    post {
        always {
            mail to: 'emilycaroline689@gmail.com',
                 subject: "Jenkins Job: ${currentBuild.fullDisplayName} - ${currentBuild.currentResult}",
                 body: "O Job ${env.JOB_NAME} (${SERVICE_NAME}) foi concluído.\n\nStatus: ${currentBuild.currentResult}.\n\nPara mais detalhes, acesse: ${env.BUILD_URL}"
        }
    }
}