pipeline {
    agent any

    environment {
        SERVICE_NAME = 'api-node-pixel'
    }

    stages {
        stage('1. Checkout do Código') {
            steps {
                // Faz o clone usando SSH e a credencial cadastrada
                git branch: 'main',
                    url: 'git@github.com:aemilymelo/TAC_containers.git',
                    credentialsId: '3b5b4ad2-789b-464a-8fa9-ca3caf01488e'
            }
        }
        stage('2. Build, Re-criação e Deploy do Serviço') {
            steps {
                script {
                    echo "Parando, reconstruindo e iniciando o serviço ${SERVICE_NAME} via docker-compose..."
                    sh "docker-compose -f ../docker-compose.yml up -d --build ${SERVICE_NAME}"
                }
            }
        }
    }
    post {
        always {
            mail to: 'emilycaroline689@gmail.com',
                 subject: "Jenkins Job: ${currentBuild.fullDisplayName} - ${currentBuild.currentResult}",
                 body: "O Job ${env.JOB_NAME} (${SERVICE_NAME}) foi concluído com o status: ${currentBuild.currentResult}.\n\nPara mais detalhes, acesse: ${env.BUILD_URL}"
        }
    }
}
